---
title: "Simulation presentation"
author: "Harrison Curtis"
date: "19/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Simulsting the tossing of a coin

```{r}
# Generate a series of uniform random numbers between 0 and 1 
coinToss <- runif(10, min=0, max=1)

coinToss <- round(coinToss)

TotalHeads <- sum(coinToss)

hist(coinToss)

allHeads <- c()
for (i in 1:10000) {
  totalHeads <- sum(round(runif(10, min = 0, max = 1)))
  allHeads <- c(allHeads,totalHeads)
}
hist(allHeads)

hist(allHeads,freq=FALSE)
```

```{r}
# Realistic sample for psychological study
R_Usample <- rnorm(n = 50, mean = 10, sd = 1.5)

mean(R_Usample)
sd(R_Usample)

hist(R_Usample, breaks= 10)

# rnorm #to use pseudorandom number generator
# #to prdicue random numbers from a normal distribution
 
# dnorm Allows for the evaluation of probaility density
# #of normal distribution as a point or set(vector) of points
# 
# pnorm  Evualuate the cumulative distribution
# 
# qnorm() Evaluate wuantile the inverse of the cumulative distribution function

## Simulate standard Normal random numbers

#Setting a seed for rnadom number genrator so that the nmbers are reproducible 
#when run together
set.seed(189)
x <- rnorm(10)   

x

x_1 <- rnorm(10, 10, 2)

x_1
```
## Simulating a linear model
$${y} = {\beta_0} + {\beta_1} + \varepsilon$$ where $$\varepsilon \sim N(0,1)$$  


